#!/bin/bash 
export WAYLAND_DISPLAY=wayland-1
export XDG_RNTIME_DIR="/run/user/$(id -u)"
# kill current hyprsunset sesion
killall -q hyprsunset

# Fetch the current hour
current_hour=$(date +"%H0000" | cut -c1-4)

# If it is 1700 to 0900 set hyprsunset to 4500
if [ "$current_hour" -ge 1700 ] || [ "$current_hour" -le 0900 ]; 
	then hyprsunset -t 4500 & disown
	     if [ -n "$DISPLAY" ]; then
		 notify-send -t 2500 'Hyprsunset' "Changing to night-time bluelight level" --icon=/home/user/Pictures/dev/Hyprland_Logo-black.png
	     fi
# otherwise set hyprsunset to 6500
	else hyprsunset -t 6500 & disown 
	     if [ -n "$DISPLAY" ]; then
		 notify-send 'Hyprsunset' "Changing to day-time bluelight level" --icon=/home/user/Pictures/dev/Hyprland_Logo-black.png
	     fi
fi

# credit: https://old.reddit.com/r/hyprland/comments/1ho4bqo/how_does_hyprsunset_work/
